In [1]:
import numpy as np
import matplotlib.pyplot as plt
import csv
from mpl_toolkits.mplot3d import Axes3D

In [2]:
data_path = "ex1data2.txt"
with open(data_path, "r", newline="") as file:
    reader = csv.reader(file)
    data = np.array(list(reader), dtype=float)

data.shape

(47, 3)

In [3]:
def h_x(theta, X):
    return X.dot(theta)

In [4]:
def normalization(X):
    sigma = np.std(X, axis=0, keepdims=True)
    mu = np.mean(X, axis=0, keepdims=True)
    return (X - mu)/sigma

X = np.reshape(data[:,0:2], (-1,2))
y = np.reshape(data[:,2], (-1,1))
m = y.shape[0]
print(X.shape)
print(y.shape)
#X = normalization(X) # to get h similar to Lin_regression_multi
X = np.append(np.ones([m,1]), X, axis=1)
print(X.shape)
print(X[:10])

(47, 2)
(47, 1)
(47, 3)
[[1.000e+00 2.104e+03 3.000e+00]
 [1.000e+00 1.600e+03 3.000e+00]
 [1.000e+00 2.400e+03 3.000e+00]
 [1.000e+00 1.416e+03 2.000e+00]
 [1.000e+00 3.000e+03 4.000e+00]
 [1.000e+00 1.985e+03 4.000e+00]
 [1.000e+00 1.534e+03 3.000e+00]
 [1.000e+00 1.427e+03 3.000e+00]
 [1.000e+00 1.380e+03 3.000e+00]
 [1.000e+00 1.494e+03 3.000e+00]]


In [5]:
X_inv = np.linalg.inv(X.T.dot(X)) 
theta = X_inv.dot(X.T).dot(y)
theta

array([[89597.9095428 ],
       [  139.21067402],
       [-8738.01911233]])

In [6]:
print(h_x(theta, X[:10]))
print(y[:10])

[[356283.1103389 ]
 [286120.93063401]
 [397489.46984811]
 [269244.1857271 ]
 [472277.85514636]
 [330979.02101847]
 [276933.02614885]
 [262037.48402896]
 [255494.58235014]
 [271364.59918814]]
[[399900.]
 [329900.]
 [369000.]
 [232000.]
 [539900.]
 [299900.]
 [314900.]
 [198999.]
 [212000.]
 [242500.]]
